name: environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - biorbd>=1.10.0
  - bioptim>=3.2.1
  - ezc3d>=1.5.17
  - scipy
  - lxml
  - pandas
  - openpyxl
  - gitpython
  - pyorerun
  - pyomeca
  - opensim-org::opensim=4.5.1
